# Solution to Advent of Code, day 5, first problem

Start with the sample input in file sample.txt:
<pre>
0,9 -> 5,9
8,0 -> 0,8
9,4 -> 3,4
2,2 -> 2,1
7,0 -> 7,4
6,4 -> 2,0
0,9 -> 2,9
3,4 -> 1,4
0,0 -> 8,8
5,5 -> 8,2
</pre>


In [68]:
# We need a 2D array, the dimension 10 is enough for the sample data
N=10

In [70]:
# use numpy to simplify certain operations on 2D arrays
import numpy as np

In [71]:
# create a 2D array N*N of int with all 0's
a = np.zeros([N, N], dtype=int)

In [72]:
print(a)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [73]:
# define my own range which goes from start to stop (inclusive),
# regardless of whether start < stop or vice versa.
def bidir_range(start, stop):
    step = -1 if start > stop else 1
    return range(start, stop + step, step)

In [74]:
list(bidir_range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [75]:
list(bidir_range(10,1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [76]:
# this draws a horizontal or vertical line in a
# by incrementing the individual cell count.
def drawline(x0, y0, x1, y1):
    global a
    if x0 == x1:
        for y in bidir_range(y0,y1):
            a[x0,y] += 1
    if y0 == y1:
        for x in bidir_range(x0,x1):
            a[x,y0] += 1

In [77]:
drawline(1,9,9,9)
print(a)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]]


In [78]:
drawline(9,1,9,9)
print(a)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 1 1 1 1 1 1 1 1 2]]


In [81]:
# read all lines from data sample
lines = open("sample.txt").readlines()
print(lines)

['0,9 -> 5,9\n', '8,0 -> 0,8\n', '9,4 -> 3,4\n', '2,2 -> 2,1\n', '7,0 -> 7,4\n', '6,4 -> 2,0\n', '0,9 -> 2,9\n', '3,4 -> 1,4\n', '0,0 -> 8,8\n', '5,5 -> 8,2\n']


In [82]:
# we now need to parse each individual line, which looks something like this
print(lines[0])

0,9 -> 5,9



In [84]:
# use regular expressions for integers to extract a list of all numbers
def parse(line):
    import re
    return re.findall(r'\d+', line)

In [86]:
# note that the numbers are still stored as strings
print(parse(lines[0]))

['0', '9', '5', '9']


In [87]:
# now reset the array and process all the lines
a = np.zeros([N, N], dtype=int)
for line in lines:
    [y0,x0,y1,x1] = parse(line)
    drawline(int(x0),int(y0),int(x1),int(y1))
print(a)

[[0 0 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 1 1 2 1 1 1 2 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [2 2 2 1 1 1 0 0 0 0]]


In [88]:
# count the number of overlaps, i.e., number of cells > 1
print(np.count_nonzero(a>1))

5


In [89]:
# Great, so code seems to be working.
# Now run it on the real data from Advent of Code
N=1000
a = np.zeros([N, N], dtype=int)
lines = open("data.txt").readlines()
for line in lines:
    [y0,x0,y1,x1] = parse(line)
    drawline(int(x0),int(y0),int(x1),int(y1))
print(np.count_nonzero(a>1))

5774
